### ISSUE TITLE
How did you implement the STE in equation 10? 

### ISSUE THREAD

**Issue by wangpichao** [layog/Accurate-Binary-Convolution-Network#1]
I read your codes carefully and it is great. And I want to know how did you implement the STE in equation 10?

**Comment by layog** [comment]
STE is required during the backpropagation only, so it is automatically handled by tensorflow. I implemented the indicator function. You can read how I implemented the indicator function in the text above `cell 7` in [ABC Notebook](https://github.com/layog/Accurate-Binary-Convolution-Network/blob/master/ABC.ipynb) (You'll need to download the notebook, as LaTeX is not properly supported by Github)

**Comment by wangpichao** [comment]
Thanks your reply@layog. I am not familiar with tensorflow, and if tensorflow could handle the STE, it would be great. I am wondering whether tensorflow could deal with the weights update?

**Comment by layog** [comment]
Yes, that is what optimizers are for. You can look at the basics of tensorflow on their website.
