### ISSUE TITLE
Val accuracy is so bad? 

### ISSUE THREAD

**Issue by MrLinNing** [layog/Accurate-Binary-Convolution-Network#3]
How to make the network more accuracy?
![image](https://user-images.githubusercontent.com/24288811/39735534-9ac9c504-52ae-11e8-9a2d-1aabf7bf7f75.png)

**Comment by layog** [comment]
It's almost impossible to reach the accuracy of the normal convolutional layers. That being said, I was able to achieve upto 92% accuracy on MNIST (using my own trained network, though I believe you can achieve higher accuracy using a pretrained network). You can try to increase the number of binary layers and ApproxConv layers and check if that gives some boost to the accuracy.
